const dataS1 = [
    {
        "H1": "CODE APOGEE",
        "H2": "First Name ",
        "H3": "Last Name ",
        "M111": "Planification Stratégique des RH",
        "M112": "Systémes de Management",
        "M113": "Audit Comptable et Financier",
        "M114": "Analyse Financiére Approfondie",
        "M115": "Finance internationale et GMP",
        "M116": "Langues Etrangéres ",
        "M117": "Compétences Douces"
    },
    {
        "H1": "MAX",
        "H2": "",
        "H3": "",
        "M111": "16",
        "M112": "17",
        "M113": "15",
        "M114": "17.75",
        "M115": "16.25",
        "M116": "15.5",
        "M117": "15"
    },
    {
        "H1": "MOYENNE",
        "H2": "",
        "H3": "",
        "M111": "13.04",
        "M112": "13.49",
        "M113": "11.32",
        "M114": "14.11",
        "M115": "13.45",
        "M116": "13.79",
        "M117": "13.68"
    },
    {
        "H1": "1703759",
        "H2": "AFANTROUSSE",
        "H3": "CHAIMAE",
        "M111": "11",
        "M112": "12",
        "M113": "10",
        "M114": "6",
        "M115": "13.08",
        "M116": "14",
        "M117": "15"
    },
    {
        "H1": "2419222",
        "H2": "AHRAOUI",
        "H3": "MOHAMED",
        "M111": "12",
        "M112": "16",
        "M113": "10.5",
        "M114": "13.75",
        "M115": "12.25",
        "M116": "12.5",
        "M117": "12"
    },
    {
        "H1": "1907982",
        "H2": "AJBILOU",
        "H3": "OUMAIMA",
        "M111": "13",
        "M112": "13.5",
        "M113": "12",
        "M114": "16.75",
        "M115": "11.2",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "2002042",
        "H2": "AJYAD",
        "H3": "YOUNES",
        "M111": "12",
        "M112": "11.5",
        "M113": "11.5",
        "M114": "16.25",
        "M115": "12.95",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "111795",
        "H2": "AOURAGH",
        "H3": "HOUSSAM",
        "M111": "15",
        "M112": "12.5",
        "M113": "10",
        "M114": "13.75",
        "M115": "13.2",
        "M116": "15",
        "M117": "15"
    },
    {
        "H1": "2101578",
        "H2": "ASHAD",
        "H3": "FATIMA",
        "M111": "11",
        "M112": "12",
        "M113": "10",
        "M114": "4",
        "M115": "11.5",
        "M116": "13",
        "M117": "13"
    },
    {
        "H1": "2102616",
        "H2": "AZAIM",
        "H3": "HOURIA",
        "M111": "14",
        "M112": "13",
        "M113": "12",
        "M114": "15.75",
        "M115": "14.65",
        "M116": "14.5",
        "M117": "13"
    },
    {
        "H1": "1410879",
        "H2": "BAALLAL",
        "H3": "IKRAM",
        "M111": "13",
        "M112": "12.5",
        "M113": "11",
        "M114": "14",
        "M115": "12.6",
        "M116": "13",
        "M117": "13"
    },
    {
        "H1": "1104845",
        "H2": "BARHIH",
        "H3": "IKRAM",
        "M111": "15",
        "M112": "15",
        "M113": "12",
        "M114": "15.25",
        "M115": "14.83",
        "M116": "13",
        "M117": "14"
    },
    {
        "H1": "1800090",
        "H2": "BAZAAROUJ",
        "H3": "ACHRAF",
        "M111": "13",
        "M112": "14",
        "M113": "10.5",
        "M114": "17.25",
        "M115": "12.85",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "1907305",
        "H2": "BELBACHIR",
        "H3": "NOUR EL HOUDA",
        "M111": "15",
        "M112": "16.5",
        "M113": "10",
        "M114": "16",
        "M115": "15.5",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "1908911",
        "H2": "BENJEDDI",
        "H3": "OMAYMA",
        "M111": "13",
        "M112": "11",
        "M113": "10.5",
        "M114": "16",
        "M115": "11.5",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "2110727",
        "H2": "BOUAYADI",
        "H3": "ANAS",
        "M111": "15",
        "M112": "12.5",
        "M113": "13",
        "M114": "14.75",
        "M115": "16.25",
        "M116": "14",
        "M117": "12"
    },
    {
        "H1": "2101703",
        "H2": "BOUDA",
        "H3": "MAROUA",
        "M111": "12",
        "M112": "16",
        "M113": "10",
        "M114": "12",
        "M115": "10.5",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "2101232",
        "H2": "BOULAKHRIF",
        "H3": "NOHAYLA",
        "M111": "exclue",
        "M112": "exclue",
        "M113": "exclue",
        "M114": "exclue",
        "M115": "exclue",
        "M116": "exclue",
        "M117": "exclue"
    },
    {
        "H1": "1709133",
        "H2": "BOURASS",
        "H3": "AYA",
        "M111": "14",
        "M112": "12.5",
        "M113": "11",
        "M114": "17.5",
        "M115": "11.8",
        "M116": "15",
        "M117": "13"
    },
    {
        "H1": "1621665",
        "H2": "BOURASSE",
        "H3": "LATIFA",
        "M111": "14",
        "M112": "11.5",
        "M113": "12.5",
        "M114": "14.75",
        "M115": "14.08",
        "M116": "14",
        "M117": "12"
    },
    {
        "H1": "1913957",
        "H2": "BUDAS",
        "H3": "ASMAE",
        "M111": "11",
        "M112": "15",
        "M113": "10",
        "M114": "6",
        "M115": "13.5",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "1416665",
        "H2": "CHEDDADI",
        "H3": "ADNANE",
        "M111": "12",
        "M112": "12",
        "M113": "10",
        "M114": "13",
        "M115": "14.5",
        "M116": "14.5",
        "M117": "14"
    },
    {
        "H1": "2419220",
        "H2": "EL ATIFI",
        "H3": "LOUBNA",
        "M111": "14",
        "M112": "16.5",
        "M113": "14",
        "M114": "16",
        "M115": "15.25",
        "M116": "13.5",
        "M117": "15"
    },
    {
        "H1": "1912705",
        "H2": "EL BERKANI",
        "H3": "NAOUFAL",
        "M111": "13",
        "M112": "13",
        "M113": "11",
        "M114": "15",
        "M115": "14.08",
        "M116": "15",
        "M117": "14"
    },
    {
        "H1": "1910171",
        "H2": "EL BOUSHABATI",
        "H3": "KAWTAR",
        "M111": "14",
        "M112": "10.5",
        "M113": "10",
        "M114": "17.75",
        "M115": "13.25",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "2419224",
        "H2": "EL GHALBZOURI",
        "H3": "NISRINE",
        "M111": "15",
        "M112": "17",
        "M113": "15",
        "M114": "16.75",
        "M115": "12.95",
        "M116": "14",
        "M117": "15"
    },
    {
        "H1": "2101231",
        "H2": "EL GHAZAOUNI",
        "H3": "SANAE",
        "M111": "15",
        "M112": "13.5",
        "M113": "14.5",
        "M114": "15.5",
        "M115": "14.95",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "1810255",
        "H2": "EL GUERMAT",
        "H3": "JAAFAR",
        "M111": "13",
        "M112": "15",
        "M113": "10",
        "M114": "14.75",
        "M115": "12.5",
        "M116": "14",
        "M117": "13"
    },
    {
        "H1": "2101937",
        "H2": "EL HACHMI",
        "H3": "HAJAR",
        "M111": "11",
        "M112": "11",
        "M113": "12",
        "M114": "17.25",
        "M115": "14.48",
        "M116": "13",
        "M117": "13"
    },
    {
        "H1": "9005659",
        "H2": "EL IDRISSI",
        "H3": "LAMIAA",
        "M111": "15",
        "M112": "14",
        "M113": "11",
        "M114": "16.5",
        "M115": "12.38",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "1909994",
        "H2": "EL JARI",
        "H3": "KAWTAR",
        "M111": "11",
        "M112": "15",
        "M113": "12.5",
        "M114": "13",
        "M115": "12.6",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "2001634",
        "H2": "EL MAJIDI",
        "H3": "LOUBNA",
        "M111": "16",
        "M112": "11",
        "M113": "14.5",
        "M114": "12.5",
        "M115": "16.25",
        "M116": "14.5",
        "M117": "14"
    },
    {
        "H1": "1620918",
        "H2": "EL-BAOUCHI",
        "H3": "HASSAN",
        "M111": "10",
        "M112": "11.5",
        "M113": "10.5",
        "M114": "14.25",
        "M115": "13",
        "M116": "13",
        "M117": "13"
    },
    {
        "H1": "2100695",
        "H2": "ESSAKKALI",
        "H3": "FATIMA",
        "M111": "10",
        "M112": "11",
        "M113": "10",
        "M114": "13",
        "M115": "12.2",
        "M116": "13",
        "M117": "12"
    },
    {
        "H1": "2419221",
        "H2": "GUENANE",
        "H3": "MOHAMMED SAMI",
        "M111": "12",
        "M112": "16",
        "M113": "14.5",
        "M114": "15.25",
        "M115": "14.65",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "2101911",
        "H2": "HAJJI",
        "H3": "CHAYMAE",
        "M111": "14",
        "M112": "13.5",
        "M113": "10",
        "M114": "14",
        "M115": "12.6",
        "M116": "13.5",
        "M117": "13"
    },
    {
        "H1": "1412196",
        "H2": "HAMMADA",
        "H3": "ABDELILAH",
        "M111": "14",
        "M112": "12",
        "M113": "11",
        "M114": "13",
        "M115": "11.45",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "2015161",
        "H2": "HARCOUCH",
        "H3": "IMANE",
        "M111": "10",
        "M112": "15.5",
        "M113": "12",
        "M114": "14",
        "M115": "13.6",
        "M116": "13",
        "M117": "12"
    },
    {
        "H1": "1909840",
        "H2": "IBRAHIMI",
        "H3": "JIHANE",
        "M111": "13",
        "M112": "11.5",
        "M113": "12.5",
        "M114": "12",
        "M115": "14.6",
        "M116": "14",
        "M117": "14"
    },
    {
        "H1": "2101000",
        "H2": "KACHIH",
        "H3": "NADIA",
        "M111": "14",
        "M112": "11",
        "M113": "13.5",
        "M114": "15",
        "M115": "13",
        "M116": "15.5",
        "M117": "14"
    },
    {
        "H1": "2101057",
        "H2": "KARNAOUI",
        "H3": "ASMAE",
        "M111": "13",
        "M112": "13.5",
        "M113": "10",
        "M114": "12",
        "M115": "13.43",
        "M116": "12.5",
        "M117": "11"
    },
    {
        "H1": "1512680",
        "H2": "KERRAZI",
        "H3": "MOHAMED",
        "M111": "14",
        "M112": "16",
        "M113": "10.5",
        "M114": "17.5",
        "M115": "15.3",
        "M116": "15",
        "M117": "14"
    },
    {
        "H1": "2419223",
        "H2": "KHACHI",
        "H3": "MOHAMMED",
        "M111": "12",
        "M112": "15.5",
        "M113": "11",
        "M114": "15",
        "M115": "12.08",
        "M116": "12.5",
        "M117": "13"
    },
    {
        "H1": "1914030",
        "H2": "KHARRAT",
        "H3": "OMAR",
        "M111": "16",
        "M112": "15",
        "M113": "10",
        "M114": "9",
        "M115": "14.25",
        "M116": "14",
        "M117": "15"
    },
    {
        "H1": "2106813",
        "H2": "LAACHACH",
        "H3": "OUMAIMA",
        "M111": "14",
        "M112": "13.5",
        "M113": "10",
        "M114": "17.5",
        "M115": "13.2",
        "M116": "14.5",
        "M117": "15"
    },
    {
        "H1": "1703051",
        "H2": "LOUKILI",
        "H3": "ACHRAF",
        "M111": "10",
        "M112": "14",
        "M113": "11",
        "M114": "14.75",
        "M115": "15",
        "M116": "13.5",
        "M117": "13"
    },
    {
        "H1": "1911457",
        "H2": "LOUKILI",
        "H3": "OUALID",
        "M111": "11",
        "M112": "14",
        "M113": "10",
        "M114": "13.5",
        "M115": "12.5",
        "M116": "12.5",
        "M117": "13"
    },
    {
        "H1": "1624126",
        "H2": "MAATOUG",
        "H3": "IKHLASS",
        "M111": "15",
        "M112": "11.5",
        "M113": "10",
        "M114": "14",
        "M115": "13.65",
        "M116": "15",
        "M117": "15"
    },
    {
        "H1": "2002022",
        "H2": "MAJJATI",
        "H3": "IKRAM",
        "M111": "14",
        "M112": "13",
        "M113": "12",
        "M114": "12",
        "M115": "14.25",
        "M116": "13.5",
        "M117": "12"
    },
    {
        "H1": "2000257",
        "H2": "MRABET",
        "H3": "JAOUHARA",
        "M111": "12",
        "M112": "14",
        "M113": "10.5",
        "M114": "15.75",
        "M115": "13.95",
        "M116": "10.5",
        "M117": "11"
    },
    {
        "H1": "1414081",
        "H2": "OUASS",
        "H3": "NABIL",
        "M111": "14",
        "M112": "14",
        "M113": "11.5",
        "M114": "13.5",
        "M115": "14.78",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "115718",
        "H2": "TAHAYATO",
        "H3": "MOURAD",
        "M111": "12",
        "M112": "16",
        "M113": "12",
        "M114": "14.5",
        "M115": "12.6",
        "M116": "13.5",
        "M117": "14"
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    },
    {
        "H1": "",
        "H2": "",
        "H3": "",
        "M111": "",
        "M112": "",
        "M113": "",
        "M114": "",
        "M115": "",
        "M116": "",
        "M117": ""
    }
]
    ;
const dataS2 = [
    {
        "CODE APOGEE": "MAX",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "18",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.5",
        "Management Strategique": "17",
        "Management de Projet": "15.7",
        "Entrepreneuriat et Innovation": "17",
        "Langues Etrangéres ": "18",
        "Culture Digitale": "16.5",
        "Moyennes": "15.67"
    },
    {
        "CODE APOGEE": "MOYENNE",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "14.18",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.96",
        "Management Strategique": "15.28",
        "Management de Projet": "13.49",
        "Entrepreneuriat et Innovation": "14.01",
        "Langues Etrangéres ": "16.72",
        "Culture Digitale": "12.87",
        "Moyennes": "14.08"
    },
    {
        "CODE APOGEE": "1703759",
        "First Name ": "AFANTROUSSE",
        "Last Name ": "CHAIMAE",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.50",
        "Management Strategique": "15.50",
        "Management de Projet": "13.80",
        "Entrepreneuriat et Innovation": "13.75",
        "Langues Etrangéres ": "15.50",
        "Culture Digitale": "13.00",
        "Moyennes": "14.29"
    },
    {
        "CODE APOGEE": "2419222",
        "First Name ": "AHRAOUI",
        "Last Name ": "MOHAMED",
        "Controle de Gestion Approfondie": "9.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "15.50",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "17.00",
        "Culture Digitale": "11.00",
        "Moyennes": "13.04"
    },
    {
        "CODE APOGEE": "1907982",
        "First Name ": "AJBILOU",
        "Last Name ": "OUMAIMA",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "13.00",
        "Moyennes": "14.44"
    },
    {
        "CODE APOGEE": "2002042",
        "First Name ": "AJYAD",
        "Last Name ": "YOUNES",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.00",
        "Management Strategique": "15.50",
        "Management de Projet": "10.10",
        "Entrepreneuriat et Innovation": "12.75",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "11.00",
        "Moyennes": "13.44"
    },
    {
        "CODE APOGEE": "111795",
        "First Name ": "AOURAGH",
        "Last Name ": "HOUSSAM",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.50",
        "Management Strategique": "16.00",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "17.75",
        "Culture Digitale": "16.50",
        "Moyennes": "15.22"
    },
    {
        "CODE APOGEE": "2101578",
        "First Name ": "ASHAD",
        "Last Name ": "FATIMA",
        "Controle de Gestion Approfondie": "16.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.00",
        "Management de Projet": "15.00",
        "Entrepreneuriat et Innovation": "11.00",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "14.00",
        "Moyennes": "14.00"
    },
    {
        "CODE APOGEE": "2102616",
        "First Name ": "AZAIM",
        "Last Name ": "HOURIA",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "15.50",
        "Management de Projet": "14.00",
        "Entrepreneuriat et Innovation": "15.50",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "13.50",
        "Moyennes": "14.93"
    },
    {
        "CODE APOGEE": "1410879",
        "First Name ": "BAALLAL",
        "Last Name ": "IKRAM",
        "Controle de Gestion Approfondie": "11.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "16.25",
        "Culture Digitale": "16.00",
        "Moyennes": "13.66"
    },
    {
        "CODE APOGEE": "1104845",
        "First Name ": "BARHIH",
        "Last Name ": "IKRAM",
        "Controle de Gestion Approfondie": "14.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "15.50",
        "Management de Projet": "15.00",
        "Entrepreneuriat et Innovation": "17.00",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "13.50",
        "Moyennes": "15.18"
    },
    {
        "CODE APOGEE": "1800090",
        "First Name ": "BAZAAROUJ",
        "Last Name ": "ACHRAF",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.50",
        "Management Strategique": "15.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "17.00",
        "Culture Digitale": "13.00",
        "Moyennes": "14.63"
    },
    {
        "CODE APOGEE": "1907305",
        "First Name ": "BELBACHIR",
        "Last Name ": "NOUR EL HOUDA",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "15.50",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "17.00",
        "Langues Etrangéres ": "17.75",
        "Culture Digitale": "13.00",
        "Moyennes": "15.38"
    },
    {
        "CODE APOGEE": "1908911",
        "First Name ": "BENJEDDI",
        "Last Name ": "OMAYMA",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.50",
        "Management Strategique": "14.50",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "16.25",
        "Langues Etrangéres ": "17.50",
        "Culture Digitale": "13.00",
        "Moyennes": "14.79"
    },
    {
        "CODE APOGEE": "2110727",
        "First Name ": "BOUAYADI",
        "Last Name ": "ANAS",
        "Controle de Gestion Approfondie": "15.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "17.00",
        "Management de Projet": "15.00",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "17.50",
        "Culture Digitale": "13.25",
        "Moyennes": "14.75"
    },
    {
        "CODE APOGEE": "2101703",
        "First Name ": "BOUDA",
        "Last Name ": "MAROUA",
        "Controle de Gestion Approfondie": "5.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "14.00",
        "Management de Projet": "10.10",
        "Entrepreneuriat et Innovation": "12.00",
        "Langues Etrangéres ": "17.75",
        "Culture Digitale": "13.00",
        "Moyennes": "11.84"
    },
    {
        "CODE APOGEE": "2101232",
        "First Name ": "BOULAKHRIF",
        "Last Name ": "NOHAYLA",
        "Controle de Gestion Approfondie": "AB",
        "Fiscalite de l\u0027Entreprise Approfondie": "AB",
        "Management Strategique": "AB",
        "Management de Projet": "AB",
        "Entrepreneuriat et Innovation": "AB",
        "Langues Etrangéres ": "AB",
        "Culture Digitale": "AB",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "1709133",
        "First Name ": "BOURASS",
        "Last Name ": "AYA",
        "Controle de Gestion Approfondie": "12.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "14.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "15.00",
        "Langues Etrangéres ": "16.75",
        "Culture Digitale": "13.00",
        "Moyennes": "13.84"
    },
    {
        "CODE APOGEE": "1621665",
        "First Name ": "BOURASSE",
        "Last Name ": "LATIFA",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "15.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "14.50",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "13.00",
        "Moyennes": "14.59"
    },
    {
        "CODE APOGEE": "1913957",
        "First Name ": "BUDAS",
        "Last Name ": "ASMAE",
        "Controle de Gestion Approfondie": "14.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "10.00",
        "Langues Etrangéres ": "16.75",
        "Culture Digitale": "13.00",
        "Moyennes": "13.48"
    },
    {
        "CODE APOGEE": "1416665",
        "First Name ": "CHEDDADI",
        "Last Name ": "ADNANE",
        "Controle de Gestion Approfondie": "10.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.00",
        "Management de Projet": "12.00",
        "Entrepreneuriat et Innovation": "13.50",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "13.00",
        "Moyennes": "13.11"
    },
    {
        "CODE APOGEE": "2419220",
        "First Name ": "EL ATIFI",
        "Last Name ": "LOUBNA",
        "Controle de Gestion Approfondie": "17.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "16.00",
        "Management de Projet": "14.00",
        "Entrepreneuriat et Innovation": "16.50",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "13.25",
        "Moyennes": "15.25"
    },
    {
        "CODE APOGEE": "1620918",
        "First Name ": "EL BAOUCHI",
        "Last Name ": "HASSAN",
        "Controle de Gestion Approfondie": "11.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.50",
        "Management Strategique": "14.50",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "12.50",
        "Moyennes": "13.61"
    },
    {
        "CODE APOGEE": "1912705",
        "First Name ": "EL BERKANI",
        "Last Name ": "NAOUFAL",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.50",
        "Management Strategique": "15.00",
        "Management de Projet": "14.00",
        "Entrepreneuriat et Innovation": "15.50",
        "Langues Etrangéres ": "16.75",
        "Culture Digitale": "13.00",
        "Moyennes": "14.96"
    },
    {
        "CODE APOGEE": "1910171",
        "First Name ": "EL BOUSHABATI",
        "Last Name ": "KAWTAR",
        "Controle de Gestion Approfondie": "12.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.00",
        "Management Strategique": "14.00",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "11.50",
        "Langues Etrangéres ": "17.50",
        "Culture Digitale": "12.75",
        "Moyennes": "13.15"
    },
    {
        "CODE APOGEE": "2419224",
        "First Name ": "EL GHALBZOURI",
        "Last Name ": "NISRINE",
        "Controle de Gestion Approfondie": "12.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "16.50",
        "Management de Projet": "14.00",
        "Entrepreneuriat et Innovation": "16.00",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "13.00",
        "Moyennes": "14.50"
    },
    {
        "CODE APOGEE": "2101231",
        "First Name ": "EL GHAZAOUNI",
        "Last Name ": "SANAE",
        "Controle de Gestion Approfondie": "12.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "15.50",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "15.00",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "16.50",
        "Moyennes": "14.45"
    },
    {
        "CODE APOGEE": "1810255",
        "First Name ": "EL GUERMAT",
        "Last Name ": "JAAFAR",
        "Controle de Gestion Approfondie": "11.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "15.00",
        "Management de Projet": "12.20",
        "Entrepreneuriat et Innovation": "15.50",
        "Langues Etrangéres ": "17.00",
        "Culture Digitale": "13.25",
        "Moyennes": "13.78"
    },
    {
        "CODE APOGEE": "2101937",
        "First Name ": "EL HACHMI",
        "Last Name ": "HAJAR",
        "Controle de Gestion Approfondie": "14.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "15.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "13.75",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "13.00",
        "Moyennes": "13.74"
    },
    {
        "CODE APOGEE": "9005659",
        "First Name ": "EL IDRISSI",
        "Last Name ": "LAMIAA",
        "Controle de Gestion Approfondie": "11.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "13.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "15.75",
        "Langues Etrangéres ": "16.25",
        "Culture Digitale": "13.50",
        "Moyennes": "13.94"
    },
    {
        "CODE APOGEE": "1909994",
        "First Name ": "EL JARI",
        "Last Name ": "KAWTAR",
        "Controle de Gestion Approfondie": "1.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.00",
        "Management Strategique": "15.50",
        "Management de Projet": "11.85",
        "Entrepreneuriat et Innovation": "15.00",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "10.00",
        "Moyennes": "11.41"
    },
    {
        "CODE APOGEE": "2001634",
        "First Name ": "EL MAJIDI",
        "Last Name ": "LOUBNA",
        "Controle de Gestion Approfondie": "15.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.50",
        "Management Strategique": "16.00",
        "Management de Projet": "15.50",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "17.00",
        "Culture Digitale": "13.50",
        "Moyennes": "14.86"
    },
    {
        "CODE APOGEE": "2100695",
        "First Name ": "ESSAKKALI",
        "Last Name ": "FATIMA",
        "Controle de Gestion Approfondie": "10.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.00",
        "Management Strategique": "13.50",
        "Management de Projet": "12.20",
        "Entrepreneuriat et Innovation": "11.75",
        "Langues Etrangéres ": "17.00",
        "Culture Digitale": "10.00",
        "Moyennes": "12.14"
    },
    {
        "CODE APOGEE": "2419221",
        "First Name ": "GUENANE",
        "Last Name ": "MOHAMMED SAMI",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.00",
        "Management Strategique": "15.50",
        "Management de Projet": "12.55",
        "Entrepreneuriat et Innovation": "16.00",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "11.00",
        "Moyennes": "14.72"
    },
    {
        "CODE APOGEE": "2101911",
        "First Name ": "HAJJI",
        "Last Name ": "CHAYMAE",
        "Controle de Gestion Approfondie": "15.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "15.50",
        "Management de Projet": "12.55",
        "Entrepreneuriat et Innovation": "13.75",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "12.50",
        "Moyennes": "14.08"
    },
    {
        "CODE APOGEE": "1412196",
        "First Name ": "HAMMADA",
        "Last Name ": "ABDELILAH",
        "Controle de Gestion Approfondie": "16.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.50",
        "Management Strategique": "15.50",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "15.00",
        "Langues Etrangéres ": "17.50",
        "Culture Digitale": "13.00",
        "Moyennes": "14.90"
    },
    {
        "CODE APOGEE": "2015161",
        "First Name ": "HARCOUCH",
        "Last Name ": "IMANE",
        "Controle de Gestion Approfondie": "10.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.50",
        "Management Strategique": "16.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "10.00",
        "Langues Etrangéres ": "15.75",
        "Culture Digitale": "11.00",
        "Moyennes": "12.31"
    },
    {
        "CODE APOGEE": "1909840",
        "First Name ": "IBRAHIMI",
        "Last Name ": "JIHANE",
        "Controle de Gestion Approfondie": "17.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "14.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "11.75",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "13.50",
        "Moyennes": "14.06"
    },
    {
        "CODE APOGEE": "2101000",
        "First Name ": "KACHIH",
        "Last Name ": "NADIA",
        "Controle de Gestion Approfondie": "17.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "10.50",
        "Management Strategique": "16.00",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "11.00",
        "Moyennes": "13.95"
    },
    {
        "CODE APOGEE": "2101057",
        "First Name ": "KARNAOUI",
        "Last Name ": "ASMAE",
        "Controle de Gestion Approfondie": "AB",
        "Fiscalite de l\u0027Entreprise Approfondie": "AB",
        "Management Strategique": "AB",
        "Management de Projet": "AB",
        "Entrepreneuriat et Innovation": "AB",
        "Langues Etrangéres ": "15.00",
        "Culture Digitale": "13.00",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "1512680",
        "First Name ": "KERRAZI",
        "Last Name ": "MOHAMED",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "14.50",
        "Management Strategique": "16.00",
        "Management de Projet": "15.70",
        "Entrepreneuriat et Innovation": "16.50",
        "Langues Etrangéres ": "16.00",
        "Culture Digitale": "13.00",
        "Moyennes": "15.67"
    },
    {
        "CODE APOGEE": "2419223",
        "First Name ": "KHACHI",
        "Last Name ": "MOHAMMED",
        "Controle de Gestion Approfondie": "12.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.50",
        "Management Strategique": "15.50",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "15.00",
        "Culture Digitale": "11.00",
        "Moyennes": "13.49"
    },
    {
        "CODE APOGEE": "1914030",
        "First Name ": "KHARRAT",
        "Last Name ": "OMAR",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.50",
        "Management Strategique": "14.50",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "17.50",
        "Culture Digitale": "11.00",
        "Moyennes": "14.34"
    },
    {
        "CODE APOGEE": "2106813",
        "First Name ": "LAACHACH",
        "Last Name ": "OUMAIMA",
        "Controle de Gestion Approfondie": "11.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "15.00",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "16.75",
        "Culture Digitale": "15.00",
        "Moyennes": "13.94"
    },
    {
        "CODE APOGEE": "1703051",
        "First Name ": "LOUKILI",
        "Last Name ": "ACHRAF",
        "Controle de Gestion Approfondie": "18.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.00",
        "Management Strategique": "15.00",
        "Management de Projet": "15.00",
        "Entrepreneuriat et Innovation": "15.50",
        "Langues Etrangéres ": "16.25",
        "Culture Digitale": "13.00",
        "Moyennes": "15.11"
    },
    {
        "CODE APOGEE": "1911457",
        "First Name ": "LOUKILI",
        "Last Name ": "OUALID",
        "Controle de Gestion Approfondie": "16.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.00",
        "Management Strategique": "16.00",
        "Management de Projet": "14.30",
        "Entrepreneuriat et Innovation": "13.00",
        "Langues Etrangéres ": "16.25",
        "Culture Digitale": "13.00",
        "Moyennes": "14.22"
    },
    {
        "CODE APOGEE": "1624126",
        "First Name ": "MAATOUG",
        "Last Name ": "IKHLASS",
        "Controle de Gestion Approfondie": "17.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "12.00",
        "Management Strategique": "15.50",
        "Management de Projet": "12.90",
        "Entrepreneuriat et Innovation": "15.00",
        "Langues Etrangéres ": "18.00",
        "Culture Digitale": "13.00",
        "Moyennes": "14.84"
    },
    {
        "CODE APOGEE": "2002022",
        "First Name ": "MAJJATI",
        "Last Name ": "IKRAM",
        "Controle de Gestion Approfondie": "11.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "14.50",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "14.00",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "13.00",
        "Moyennes": "13.44"
    },
    {
        "CODE APOGEE": "2000257",
        "First Name ": "MRABET",
        "Last Name ": "JAOUHARA",
        "Controle de Gestion Approfondie": "12.50",
        "Fiscalite de l\u0027Entreprise Approfondie": "11.50",
        "Management Strategique": "16.50",
        "Management de Projet": "14.50",
        "Entrepreneuriat et Innovation": "14.25",
        "Langues Etrangéres ": "17.25",
        "Culture Digitale": "12.50",
        "Moyennes": "14.14"
    },
    {
        "CODE APOGEE": "1414081",
        "First Name ": "OUASS",
        "Last Name ": "NABIL",
        "Controle de Gestion Approfondie": "11.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.50",
        "Management Strategique": "15.50",
        "Management de Projet": "13.25",
        "Entrepreneuriat et Innovation": "13.50",
        "Langues Etrangéres ": "16.25",
        "Culture Digitale": "13.00",
        "Moyennes": "13.71"
    },
    {
        "CODE APOGEE": "115718",
        "First Name ": "TAHAYATO",
        "Last Name ": "MOURAD",
        "Controle de Gestion Approfondie": "15.00",
        "Fiscalite de l\u0027Entreprise Approfondie": "13.00",
        "Management Strategique": "16.00",
        "Management de Projet": "13.60",
        "Entrepreneuriat et Innovation": "13.50",
        "Langues Etrangéres ": "16.50",
        "Culture Digitale": "12.25",
        "Moyennes": "14.26"
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    },
    {
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Controle de Gestion Approfondie": "",
        "Fiscalite de l\u0027Entreprise Approfondie": "",
        "Management Strategique": "",
        "Management de Projet": "",
        "Entrepreneuriat et Innovation": "",
        "Langues Etrangéres ": "",
        "Culture Digitale": "",
        "Moyennes": ""
    }
]
    ;
const dataS3 = [
    {
        "NUMERO": "MAX",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "17",
        "Comptabilite Approfondie": "17.5",
        "Management de la Logistique": "16",
        "Diagnostic Strategique": "15.5",
        "Gestion de Portefeuille": "17.5",
        "Anglais": "16",
        "Logiciels et Analyse de donnes": "16",
        "Moyennes": "15.09"
    },
    {
        "NUMERO": "MOYENNE",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "15.64",
        "Comptabilite Approfondie": "8.33",
        "Management de la Logistique": "11.66",
        "Diagnostic Strategique": "13.46",
        "Gestion de Portefeuille": "14.78",
        "Anglais": "14.06",
        "Logiciels et Analyse de donnes": "12.35",
        "Moyennes": "12.9"
    },
    {
        "NUMERO": "1",
        "CODE APOGEE": "2001634",
        "First Name ": "EL MAJIDI",
        "Last Name ": "LOUBNA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "12.00",
        "Management de la Logistique": "16.00",
        "Diagnostic Strategique": "14.00",
        "Gestion de Portefeuille": "17.20",
        "Anglais": "13.50",
        "Logiciels et Analyse de donnes": "11.50",
        "Moyennes": "14.24"
    },
    {
        "NUMERO": "2",
        "CODE APOGEE": "2102616",
        "First Name ": "AZAIM",
        "Last Name ": "HOURIA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "7.00",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "17.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "16.00",
        "Moyennes": "13.31"
    },
    {
        "NUMERO": "3",
        "CODE APOGEE": "9005659",
        "First Name ": "EL IDRISSI",
        "Last Name ": "LAMIAA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "5.00",
        "Management de la Logistique": "13.00",
        "Diagnostic Strategique": "14.00",
        "Gestion de Portefeuille": "13.60",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "12.00",
        "Moyennes": "12.59"
    },
    {
        "NUMERO": "4",
        "CODE APOGEE": "2110727",
        "First Name ": "BOUAYADI",
        "Last Name ": "ANAS",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "13.00",
        "Management de la Logistique": "8.50",
        "Diagnostic Strategique": "15.50",
        "Gestion de Portefeuille": "17.20",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "12.50",
        "Moyennes": "13.96"
    },
    {
        "NUMERO": "5",
        "CODE APOGEE": "2419220",
        "First Name ": "EL ATIFI",
        "Last Name ": "LOUBNA",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "2.50",
        "Management de la Logistique": "14.50",
        "Diagnostic Strategique": "15.00",
        "Gestion de Portefeuille": "17.50",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "13.29"
    },
    {
        "NUMERO": "6",
        "CODE APOGEE": "1104845",
        "First Name ": "BARHIH",
        "Last Name ": "IKRAM",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "2.50",
        "Management de la Logistique": "13.50",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "16.60",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "12.66"
    },
    {
        "NUMERO": "7",
        "CODE APOGEE": "2106813",
        "First Name ": "LAACHACH",
        "Last Name ": "OUMAIMA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "13.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "16.30",
        "Anglais": "13.50",
        "Logiciels et Analyse de donnes": "14.00",
        "Moyennes": "13.11"
    },
    {
        "NUMERO": "8",
        "CODE APOGEE": "1800090",
        "First Name ": "BAZAAROUJ",
        "Last Name ": "ACHRAF",
        "Evaluation de l\u0027entreprise": "16.50",
        "Comptabilite Approfondie": "15.00",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "15.00",
        "Gestion de Portefeuille": "16.60",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "10.00",
        "Moyennes": "13.73"
    },
    {
        "NUMERO": "9",
        "CODE APOGEE": "2101937",
        "First Name ": "EL HACHMI",
        "Last Name ": "HAJAR",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "17.50",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "17.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "12.50",
        "Moyennes": "14.24"
    },
    {
        "NUMERO": "10",
        "CODE APOGEE": "115718",
        "First Name ": "TAHAYATO",
        "Last Name ": "MOURAD",
        "Evaluation de l\u0027entreprise": "16.50",
        "Comptabilite Approfondie": "13.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "14.50",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "10.00",
        "Moyennes": "13.50"
    },
    {
        "NUMERO": "11",
        "CODE APOGEE": "2101231",
        "First Name ": "EL GHAZAOUNI",
        "Last Name ": "SANAE",
        "Evaluation de l\u0027entreprise": "16.50",
        "Comptabilite Approfondie": "2.00",
        "Management de la Logistique": "8.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "16.60",
        "Anglais": "14.50",
        "Logiciels et Analyse de donnes": "10.50",
        "Moyennes": "11.66"
    },
    {
        "NUMERO": "12",
        "CODE APOGEE": "1412196",
        "First Name ": "HAMMADA",
        "Last Name ": "ABDELILAH",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "8.50",
        "Management de la Logistique": "13.00",
        "Diagnostic Strategique": "14.50",
        "Gestion de Portefeuille": "13.90",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "12.84"
    },
    {
        "NUMERO": "13",
        "CODE APOGEE": "2101000",
        "First Name ": "KACHIH",
        "Last Name ": "NADIA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "2.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "12.00",
        "Gestion de Portefeuille": "16.60",
        "Anglais": "16.00",
        "Logiciels et Analyse de donnes": "16.00",
        "Moyennes": "12.87"
    },
    {
        "NUMERO": "14",
        "CODE APOGEE": "1709133",
        "First Name ": "BOURASS",
        "Last Name ": "AYA",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "11.00",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "12.50",
        "Gestion de Portefeuille": "12.70",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "12.31"
    },
    {
        "NUMERO": "15",
        "CODE APOGEE": "1908911",
        "First Name ": "BENJEDDI",
        "Last Name ": "OMAYMA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "15.00",
        "Management de la Logistique": "8.50",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "14.80",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "12.00",
        "Moyennes": "13.11"
    },
    {
        "NUMERO": "16",
        "CODE APOGEE": "2100695",
        "First Name ": "ESSAKKALI",
        "Last Name ": "FATIMA",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "8.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "15.10",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "14.00",
        "Moyennes": "12.37"
    },
    {
        "NUMERO": "17",
        "CODE APOGEE": "2101057",
        "First Name ": "KARNAOUI",
        "Last Name ": "ASMAE",
        "Evaluation de l\u0027entreprise": "EXC",
        "Comptabilite Approfondie": "EXC",
        "Management de la Logistique": "EXC",
        "Diagnostic Strategique": "EXC",
        "Gestion de Portefeuille": "EXC",
        "Anglais": "EXC",
        "Logiciels et Analyse de donnes": "EXC",
        "Moyennes": "NaN"
    },
    {
        "NUMERO": "18",
        "CODE APOGEE": "2101911",
        "First Name ": "HAJJI",
        "Last Name ": "CHAYMAE",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "13.50",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "15.10",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "13.30"
    },
    {
        "NUMERO": "19",
        "CODE APOGEE": "1914030",
        "First Name ": "KHARRAT",
        "Last Name ": "OMAR",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "9.00",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "15.00",
        "Gestion de Portefeuille": "14.50",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "12.50",
        "Moyennes": "12.86"
    },
    {
        "NUMERO": "20",
        "CODE APOGEE": "2419221",
        "First Name ": "GUENANE",
        "Last Name ": "MOHAMMED SAMI",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "14.00",
        "Management de la Logistique": "15.00",
        "Diagnostic Strategique": "15.00",
        "Gestion de Portefeuille": "14.80",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "10.00",
        "Moyennes": "14.26"
    },
    {
        "NUMERO": "21",
        "CODE APOGEE": "1911457",
        "First Name ": "LOUKILI",
        "Last Name ": "OUALID",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "3.00",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "14.00",
        "Gestion de Portefeuille": "14.20",
        "Anglais": "12.00",
        "Logiciels et Analyse de donnes": "13.00",
        "Moyennes": "11.60"
    },
    {
        "NUMERO": "22",
        "CODE APOGEE": "1910171",
        "First Name ": "EL BOUSHABATI",
        "Last Name ": "KAWTAR",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "6.50",
        "Management de la Logistique": "11.50",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "15.40",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "12.56"
    },
    {
        "NUMERO": "23",
        "CODE APOGEE": "2015161",
        "First Name ": "HARCOUCH",
        "Last Name ": "IMANE",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "12.50",
        "Gestion de Portefeuille": "13.90",
        "Anglais": "14.50",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "12.56"
    },
    {
        "NUMERO": "24",
        "CODE APOGEE": "111795",
        "First Name ": "AOURAGH",
        "Last Name ": "HOUSSAM",
        "Evaluation de l\u0027entreprise": "17.00",
        "Comptabilite Approfondie": "10.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "14.00",
        "Gestion de Portefeuille": "15.10",
        "Anglais": "15.50",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "13.51"
    },
    {
        "NUMERO": "25",
        "CODE APOGEE": "1810255",
        "First Name ": "EL GUERMAT",
        "Last Name ": "JAAFAR",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "5.00",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "15.70",
        "Anglais": "15.50",
        "Logiciels et Analyse de donnes": "11.50",
        "Moyennes": "12.53"
    },
    {
        "NUMERO": "26",
        "CODE APOGEE": "1913957",
        "First Name ": "BUDAS",
        "Last Name ": "ASMAE",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "11.50",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "15.40",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "14.00",
        "Moyennes": "13.34"
    },
    {
        "NUMERO": "27",
        "CODE APOGEE": "2000257",
        "First Name ": "MRABET",
        "Last Name ": "JAOUHARA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "5.00",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "14.80",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "14.00",
        "Moyennes": "12.47"
    },
    {
        "NUMERO": "28",
        "CODE APOGEE": "2101578",
        "First Name ": "ASHAD",
        "Last Name ": "FATIMA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "3.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "11.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "11.50",
        "Moyennes": "11.39"
    },
    {
        "NUMERO": "29",
        "CODE APOGEE": "1909840",
        "First Name ": "IBRAHIMI",
        "Last Name ": "JIHANE",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "7.50",
        "Management de la Logistique": "7.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "14.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "12.50",
        "Moyennes": "11.89"
    },
    {
        "NUMERO": "30",
        "CODE APOGEE": "2419223",
        "First Name ": "KHACHI",
        "Last Name ": "MOHAMMED",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "11.50",
        "Management de la Logistique": "12.50",
        "Diagnostic Strategique": "14.00",
        "Gestion de Portefeuille": "14.80",
        "Anglais": "12.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "13.04"
    },
    {
        "NUMERO": "31",
        "CODE APOGEE": "2101232",
        "First Name ": "BOULAKHRIF",
        "Last Name ": "NOHAYLA",
        "Evaluation de l\u0027entreprise": "EXC",
        "Comptabilite Approfondie": "EXC",
        "Management de la Logistique": "EXC",
        "Diagnostic Strategique": "EXC",
        "Gestion de Portefeuille": "EXC",
        "Anglais": "EXC",
        "Logiciels et Analyse de donnes": "EXC",
        "Moyennes": "NaN"
    },
    {
        "NUMERO": "32",
        "CODE APOGEE": "1912705",
        "First Name ": "EL BERKANI",
        "Last Name ": "NAOUFAL",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "13.00",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "11.00",
        "Gestion de Portefeuille": "16.00",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "13.14"
    },
    {
        "NUMERO": "33",
        "CODE APOGEE": "2419222",
        "First Name ": "AHRAOUI",
        "Last Name ": "MOHAMED",
        "Evaluation de l\u0027entreprise": "16.50",
        "Comptabilite Approfondie": "1.00",
        "Management de la Logistique": "14.00",
        "Diagnostic Strategique": "14.50",
        "Gestion de Portefeuille": "13.60",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "10.00",
        "Moyennes": "11.94"
    },
    {
        "NUMERO": "34",
        "CODE APOGEE": "1907982",
        "First Name ": "AJBILOU",
        "Last Name ": "OUMAIMA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "17.50",
        "Management de la Logistique": "13.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "16.00",
        "Anglais": "14.50",
        "Logiciels et Analyse de donnes": "12.50",
        "Moyennes": "14.64"
    },
    {
        "NUMERO": "35",
        "CODE APOGEE": "2101703",
        "First Name ": "BOUDA",
        "Last Name ": "MAROUA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "4.50",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "10.00",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "10.00",
        "Moyennes": "11.00"
    },
    {
        "NUMERO": "36",
        "CODE APOGEE": "2002022",
        "First Name ": "MAJJATI",
        "Last Name ": "IKRAM",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "4.00",
        "Management de la Logistique": "11.50",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "11.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "14.00",
        "Moyennes": "11.81"
    },
    {
        "NUMERO": "37",
        "CODE APOGEE": "1909994",
        "First Name ": "EL JARI",
        "Last Name ": "KAWTAR",
        "Evaluation de l\u0027entreprise": "16.50",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "13.00",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "12.43"
    },
    {
        "NUMERO": "38",
        "CODE APOGEE": "1410879",
        "First Name ": "BAALLAL",
        "Last Name ": "IKRAM",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "8.50",
        "Diagnostic Strategique": "12.00",
        "Gestion de Portefeuille": "13.90",
        "Anglais": "14.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "11.84"
    },
    {
        "NUMERO": "39",
        "CODE APOGEE": "1621665",
        "First Name ": "BOURASSE",
        "Last Name ": "LATIFA",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "10.00",
        "Management de la Logistique": "13.00",
        "Diagnostic Strategique": "11.50",
        "Gestion de Portefeuille": "16.00",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "15.00",
        "Moyennes": "13.71"
    },
    {
        "NUMERO": "40",
        "CODE APOGEE": "1624126",
        "First Name ": "MAATOUG",
        "Last Name ": "IKHLASS",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "11.50",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "15.40",
        "Anglais": "16.00",
        "Logiciels et Analyse de donnes": "10.50",
        "Moyennes": "13.49"
    },
    {
        "NUMERO": "41",
        "CODE APOGEE": "1416665",
        "First Name ": "CHEDDADI",
        "Last Name ": "ADNANE",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "5.50",
        "Management de la Logistique": "11.00",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "11.20",
        "Anglais": "13.00",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "11.46"
    },
    {
        "NUMERO": "42",
        "CODE APOGEE": "1703051",
        "First Name ": "LOUKILI",
        "Last Name ": "ACHRAF",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "8.00",
        "Management de la Logistique": "11.50",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "16.00",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "11.50",
        "Moyennes": "13.00"
    },
    {
        "NUMERO": "43",
        "CODE APOGEE": "1512680",
        "First Name ": "KERRAZI",
        "Last Name ": "MOHAMED",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "12.00",
        "Management de la Logistique": "14.00",
        "Diagnostic Strategique": "14.50",
        "Gestion de Portefeuille": "16.90",
        "Anglais": "13.50",
        "Logiciels et Analyse de donnes": "15.00",
        "Moyennes": "14.49"
    },
    {
        "NUMERO": "44",
        "CODE APOGEE": "1703759",
        "First Name ": "AFANTROUSSE",
        "Last Name ": "CHAIMAE",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "13.00",
        "Management de la Logistique": "11.50",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "13.00",
        "Anglais": "14.50",
        "Logiciels et Analyse de donnes": "12.00",
        "Moyennes": "13.21"
    },
    {
        "NUMERO": "45",
        "CODE APOGEE": "1620918",
        "First Name ": "EL BAOUCHI",
        "Last Name ": "HASSAN",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "14.00",
        "Diagnostic Strategique": "12.50",
        "Gestion de Portefeuille": "14.50",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "12.00",
        "Moyennes": "12.79"
    },
    {
        "NUMERO": "46",
        "CODE APOGEE": "2002042",
        "First Name ": "AJYAD",
        "Last Name ": "YOUNES",
        "Evaluation de l\u0027entreprise": "15.00",
        "Comptabilite Approfondie": "4.50",
        "Management de la Logistique": "10.00",
        "Diagnostic Strategique": "12.00",
        "Gestion de Portefeuille": "10.00",
        "Anglais": "15.00",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "11.43"
    },
    {
        "NUMERO": "47",
        "CODE APOGEE": "1907305",
        "First Name ": "BELBACHIR",
        "Last Name ": "NOUR EL HOUDA",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "15.00",
        "Management de la Logistique": "15.50",
        "Diagnostic Strategique": "13.50",
        "Gestion de Portefeuille": "16.60",
        "Anglais": "15.50",
        "Logiciels et Analyse de donnes": "13.50",
        "Moyennes": "15.09"
    },
    {
        "NUMERO": "48",
        "CODE APOGEE": "1414081",
        "First Name ": "OUASS",
        "Last Name ": "NABIL",
        "Evaluation de l\u0027entreprise": "15.50",
        "Comptabilite Approfondie": "4.50",
        "Management de la Logistique": "15.50",
        "Diagnostic Strategique": "15.00",
        "Gestion de Portefeuille": "13.60",
        "Anglais": "15.50",
        "Logiciels et Analyse de donnes": "12.00",
        "Moyennes": "13.09"
    },
    {
        "NUMERO": "49",
        "CODE APOGEE": "2419224",
        "First Name ": "EL GHALBZOURI",
        "Last Name ": "NISRINE",
        "Evaluation de l\u0027entreprise": "16.00",
        "Comptabilite Approfondie": "6.00",
        "Management de la Logistique": "12.00",
        "Diagnostic Strategique": "13.00",
        "Gestion de Portefeuille": "15.10",
        "Anglais": "14.50",
        "Logiciels et Analyse de donnes": "11.00",
        "Moyennes": "12.51"
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    },
    {
        "NUMERO": "",
        "CODE APOGEE": "",
        "First Name ": "",
        "Last Name ": "",
        "Evaluation de l\u0027entreprise": "",
        "Comptabilite Approfondie": "",
        "Management de la Logistique": "",
        "Diagnostic Strategique": "",
        "Gestion de Portefeuille": "",
        "Anglais": "",
        "Logiciels et Analyse de donnes": "",
        "Moyennes": ""
    }
]
    ;

